# -*- coding: utf-8 -*-
"""itinnovateStock.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v_0oaicJWa5C8hM6UK9eZL6wEqJB5UiM

# ITINNOVATE STOCK Classification model using the Fast AI Library

##Import libraries
"""

#hide
# !pip install -Uqq fastbook
import fastbook
fastbook.setup_book()

# pip install  torch==1.8.0

#hide
from fastbook import *
from fastai.vision.widgets import *

"""### UPLOAD AND UNZIP DATA

"""

import os
if not os.path.exists('images'):
    os.makedirs('images')

#from google.colab import files

uploaded = files.upload()

#from google.colab import files

# !unzip images.zip -d images/

path = Path('images')
print(path)

import os
arr = os.listdir('images/images/')
print(arr)



"""# Build model"""

shareData = DataBlock(
    blocks=(ImageBlock, CategoryBlock), 
    get_items=get_image_files, 
    splitter=RandomSplitter(valid_pct=0.2, seed=42),
    get_y=parent_label
     )

path = Path('images/images/')
dls = shareData.dataloaders(path)

# Show images
dls.valid.show_batch(max_n=7, nrows=1)

"""#Training Your Model"""

shareData = shareData.new()
dls = shareData.dataloaders(path, batch_size=16)

print(dls)

learn.lr_find()

#learn = cnn_learner(dls, resnet34, metrics=error_rate)
learn = cnn_learner(dls, resnet50, metrics=error_rate)
learn.lr_find()

#learn.fine_tune(10)

learn.fit_one_cycle(10,lr_max=slice(10e-3, 10e-4))

"""## Evaluating the model

"""

interp = ClassificationInterpretation.from_learner(learn)
interp.plot_confusion_matrix(
                                normalize=True )